def calc(a, b, symbol):
    if symbol == '*':
        return a * b
    elif symbol == '/':
        return a / b
    elif symbol == '+':
        return a + b
    elif symbol == '-':
        return a - b
